name: Development Node server build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

# Cannot use below code because container-signer stack not designed to be used in Dev    
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 60
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - name: Upload to ECR and tag
#         uses: alphagov/di-devplatform-upload-action-ecr@1.0.1
#         with:
#           role-to-assume-arn: ${{ secrets.DEV_ROLE_TO_ASSUME }}
#           container-sign-kms-key-arn: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
#           ecr-repo-name: ${{ secrets.DEV_ECR_REPOSITORY }}
#           artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_BUCKET }}

jobs:
  dockerBuildAndPush:
    name: Docker build and push
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.DEV_ROLE_TO_ASSUME }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          DEV_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DEV_ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          docker build -t $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$GITHUB_SHA .
          docker push $DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$GITHUB_SHA
      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t template.yaml

      - name: Update SAM template with ECR image
        env:
          DEV_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DEV_ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          sed -i "s|CONTAINER-IMAGE-PLACEHOLDER|$DEV_ECR_REGISTRY/$DEV_ECR_REPOSITORY:$GITHUB_SHA|" template.yaml
      - name: Create template.yaml and sha zip file
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          sam build
          mv .aws-sam/build/template.yaml cf-template.yaml
          zip template.zip cf-template.yaml
      - name: Upload CloudFormation artifacts to S3
        env:
          DEV_ARTIFACT_BUCKET: ${{ secrets.DEV_ARTIFACT_BUCKET }}
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          aws s3 cp template.zip "s3://$DEV_ARTIFACT_BUCKET/template.zip" --metadata "repository=$GITHUB_REPOSITORY,commitsha=$GITHUB_SHA"